apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: shan0809/demo-kotlin2:2.0
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
