//package com.example.demokotlin
//
//import org.junit.jupiter.api.Test
//import org.springframework.boot.test.context.SpringBootTest
//
//@SpringBootTest
//class DemoKotlinApplicationTests {
//
//	@Test
//	fun contextLoads() {
//	}
//
//}


///*
// * This Kotlin source file was generated by the Gradle 'init' task.
// */
//package demo.kotlinhelloworld
//
//import kotlin.test.Test
//import kotlin.test.assertNotNull
//
//class AppTest {
//	@Test fun appHasAGreeting() {
//		val classUnderTest = App()
//		assertNotNull(classUnderTest.greeting, "app should have a greeting")
//	}
//}
